"""Telegram (OpenID Connect) sign-in for Vertigo.

Vertigo is normally protected by per-profile PINs. When OIDC is enabled the
outer gate becomes Telegram instead, and each Telegram account is mapped to a
Vertigo profile (created on first sign-in), so libraries stay separated.

Configuration comes from the environment so the launchd service can hold it:

* ``VERTIGO_OIDC_ENABLED``      — ``1``/``true`` to require Telegram sign-in
* ``VERTIGO_OIDC_CLIENT_ID``    — the bot's numeric id from @BotFather
* ``VERTIGO_OIDC_CLIENT_SECRET``— the Client Secret from @BotFather
* ``VERTIGO_OIDC_REDIRECT_URI`` — optional explicit callback URL
* ``VERTIGO_PUBLIC_URL``        — e.g. ``https://vertigo.atomoblako.ru``
"""

from __future__ import annotations

import json
import os
import secrets as _secrets
from pathlib import Path

from . import config

#: ``src/vertigo/oidc.py`` -> project root (where ``.streamlit/`` lives).
PROJECT_ROOT = Path(__file__).resolve().parents[2]
PROVIDER = "telegram"
METADATA_URL = "https://oauth.telegram.org/.well-known/openid-configuration"
DEFAULT_SCOPE = "openid profile"


def _flag(name: str) -> bool:
    return os.environ.get(name, "").strip().lower() in {"1", "true", "yes", "on"}


def enabled() -> bool:
    """Return whether Telegram sign-in is configured and requested."""
    return _flag("VERTIGO_OIDC_ENABLED") and bool(client_id()) and bool(client_secret())


def client_id() -> str:
    return os.environ.get("VERTIGO_OIDC_CLIENT_ID", "").strip()


def client_secret() -> str:
    return os.environ.get("VERTIGO_OIDC_CLIENT_SECRET", "").strip()


def redirect_uri() -> str:
    explicit = os.environ.get("VERTIGO_OIDC_REDIRECT_URI", "").strip()
    if explicit:
        return explicit
    public = os.environ.get("VERTIGO_PUBLIC_URL", "").rstrip("/")
    if public:
        return f"{public}/oauth2callback"
    port = os.environ.get("VERTIGO_PORT", "8600")
    return f"http://localhost:{port}/oauth2callback"


def cookie_secret() -> str:
    """Return a stable cookie-signing secret, generating one on first use."""
    existing = config.load_config().get("oidc_cookie_secret")
    if existing:
        return str(existing)
    value = _secrets.token_urlsafe(48)
    config.update_config(oidc_cookie_secret=value)
    return value


def secrets_path() -> Path:
    return PROJECT_ROOT / ".streamlit" / "secrets.toml"


def render_secrets() -> str:
    return "\n".join(
        [
            "# Generated by Vertigo for Telegram sign-in — keep it private.",
            "",
            "[auth]",
            f"redirect_uri = {json.dumps(redirect_uri())}",
            f"cookie_secret = {json.dumps(cookie_secret())}",
            "",
            f"[auth.{PROVIDER}]",
            f"client_id = {json.dumps(client_id())}",
            f"client_secret = {json.dumps(client_secret())}",
            f"server_metadata_url = {json.dumps(METADATA_URL)}",
            f"client_kwargs = {{ scope = {json.dumps(DEFAULT_SCOPE)} }}",
            "",
        ]
    )


def write_secrets() -> Path | None:
    """Write Streamlit's ``secrets.toml`` when Telegram sign-in is enabled."""
    if not enabled():
        return None
    path = secrets_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_secrets(), encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return path


# --------------------------------------------------------------------------- #
# Streamlit helpers
# --------------------------------------------------------------------------- #
def is_logged_in() -> bool:
    try:
        import streamlit as st

        return bool(st.user.is_logged_in)
    except Exception:  # noqa: BLE001
        return False


def subject() -> str:
    """Return the stable Telegram subject identifier."""
    try:
        import streamlit as st

        for key in ("sub", "id"):
            value = getattr(st.user, key, None)
            if value:
                return str(value)
    except Exception:  # noqa: BLE001
        return ""
    return ""


def display_name() -> str:
    try:
        import streamlit as st

        for key in ("name", "preferred_username", "given_name"):
            value = getattr(st.user, key, None)
            if value:
                return str(value)
    except Exception:  # noqa: BLE001
        return ""
    return ""


def username() -> str:
    try:
        import streamlit as st

        return str(getattr(st.user, "preferred_username", "") or "")
    except Exception:  # noqa: BLE001
        return ""
